### ISSUE TITLE
File imports with \\ don't work

### ISSUE THREAD

**Issue by floatforty** [IvanLink-py/Area-the-game#1]
While trying to lauch the game, I have encountered several exceptions, example (user path replaced with ~):
```Traceback (most recent call last):
  File "Area the game.py", line 1564, in <module>
    menu.mainloop()
  File "Area the game.py", line 949, in mainloop
    back = pygame.image.load(r"Images\main\Background.png")
FileNotFoundError: No file 'Images\main\Background.png' found in working directory '~/Games/Area-the-game-master'.
```
I've managed to fix it by replacing all backslashes and double backslashes with single slashes. 
Platform: Linux

**Comment by IvanLink-py** [comment]
Thanks.
